version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - ./secrets/.env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.local
    command: gunicorn social_media_tool.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./secrets/.env.local
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - db
  nginx:
    build: ./nginx/local/
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
